name: build and package app

on: 
  push:
    branches: 
      - master

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Upload source code artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-code
          path: .

  build:
    needs: checkout
    runs-on: ubuntu-latest
    # Runs the entire build job inside a container with Maven and Java pre-installed
    container: maven:3.9-eclipse-temurin-17
    
    steps:
      - name: Download source code artifact
        uses: actions/download-artifact@v4
        with:
          name: source-code
          
      - name: Build with Maven
        run: mvn clean package
